"""Surfaced-retraction detection + reconcile wiring (the advance-gate FP escape valve).

surfaced_retraction_locations(text) returns the paths the assistant EXPLICITLY and
REASON-BOUND retracts, so run_stop_checks can clear (status='retracted') a legitimately-dropped
commitment before the advance gate runs. The design is REASON-BOUND on purpose (mirrors
retraction.reconcile + detect_hidden_retraction): a bare "dropping X" with NO reason does NOT
clear — an unexplained drop is exactly the hidden retraction the advance gate should still
catch. The cases below were hardened from a 4-lens adversarial design audit (negation, wrong
subject, interrogative, conditional, accidental loss, recommit, code-fence, domain homonyms).

The positive controls (must clear) and the FP guards (must NOT clear) together form a
contamination canary: a blanket clear-all reds the FP guards; a clear-none reds the controls.
"""
import sqlite3

from makoto.verdict.retraction import surfaced_retraction_locations as surfaced
from makoto.session import commitments as C
def _has(text, path):
    from makoto.checks import normalize_path
    return normalize_path(path) in surfaced(text)


# --- positive controls: a reason-bound retraction CLEARS ----------------------------------
def test_active_verb_with_reason_clears():
    assert _has("Skipping src/cache.py for this sprint per your note — deprioritizing it.",
                "src/cache.py")


def test_post_positive_predicate_clears():
    assert _has("src/auth.py is out of scope now — we settled that earlier.", "src/auth.py")


def test_park_with_scope_clears():
    assert _has("Parking src/auth.py for the next cycle.", "src/auth.py")


def test_negated_production_frame_with_reason_clears():
    # "do not add X this round" (per the user) is a retraction, not a promise
    assert _has("Per your request, do not add src/auth.py this round.", "src/auth.py")


def test_passive_post_positive_clears():
    assert _has("src/auth.py was dropped from this milestone.", "src/auth.py")


def test_coordination_list_clears_both():
    s = surfaced("dropping src/cache.py and src/auth.py for this sprint")
    from makoto.checks import normalize_path as N
    assert N("src/cache.py") in s and N("src/auth.py") in s


# --- FP guards: each near-miss must stay INERT (no clear) ----------------------------------
def test_negated_retraction_verb_is_inert():
    # "NOT skipping X" re-affirms the commitment -> must not clear
    assert not _has("I am NOT skipping src/auth.py this time — it ships in this sprint.",
                    "src/auth.py")


def test_wrong_subject_is_inert():
    # subject is 'you' (the user), not the assistant dropping its own promise
    assert not _has("you won't need to touch src/auth.py since it's autogenerated on build.",
                    "src/auth.py")


def test_interrogative_is_inert():
    assert not _has("Should I skip src/cache.py, or keep it in scope?", "src/cache.py")


def test_conditional_is_inert():
    assert not _has("If the integration tests fail, we will drop src/cache.py.", "src/cache.py")


def test_accidental_loss_is_inert():
    assert not _has("I accidentally dropped src/cache.py from the last commit — fixing now.",
                    "src/cache.py")


def test_domain_homonym_without_reason_is_inert():
    # SQL 'drop the temp rows' governs a different noun and carries no retraction reason
    assert not _has("drop the temp rows before writing to db/schema.sql in the migration.",
                    "db/schema.sql")


def test_bare_drop_no_reason_is_inert():
    # REASON-BOUND: a bare drop is a HIDDEN retraction -> must NOT clear (advance should fire)
    assert not _has("Dropping src/cache.py.", "src/cache.py")


def test_code_fence_output_is_inert():
    assert not _has("Output:\n```\nWARNING: skipping migration db/0001.sql (already applied)\n```",
                    "db/0001.sql")


def test_recommit_reversal_is_inert():
    assert not _has("I was going to skip src/auth.py, but on reflection I will add it this sprint.",
                    "src/auth.py")


# --- firewall: a retraction of a DIFFERENT path must not clear the committed one -----------
def test_firewall_similar_path_does_not_cross_clear():
    s = surfaced("skipping src/auth_helper.py for now, but src/auth.py is still on the list")
    from makoto.checks import normalize_path as N
    assert N("src/auth_helper.py") in s          # the helper IS retracted (reason 'for now')
    assert N("src/auth.py") not in s             # the committed module is NOT (firewall holds)


def test_firewall_adversative_kept_path_not_cleared():
    # review finding (major): "dropping A for now but B is still needed" must clear ONLY A.
    s = surfaced("dropping utils/cache.py for now but src/cache.py is still needed")
    from makoto.checks import normalize_path as N
    assert N("utils/cache.py") in s
    assert N("src/cache.py") not in s            # contrasted away by "but ... still needed"


def test_user_asked_supersession_clears():
    # "you asked me to" is a canonical user-supersession reason (reconcile's U-leg)
    assert _has("Dropping src/auth.py — you asked me to deprioritize it.", "src/auth.py")


def test_reported_user_speech_does_not_clear():
    # "You said to skip X" is REPORTED speech (a forged-supersession risk), not the AI acting
    assert not _has("You said to skip src/cache.py, so I logged it and moved on.", "src/cache.py")


def test_recommit_past_tense_added_vetoes_clear():
    # "skip X ... but I added it" — past-tense production discharges; must not clear
    assert not _has("You asked me to skip src/auth.py, but I added it anyway because tests needed it.",
                    "src/auth.py")


def test_failsafe_returns_set_never_raises():
    assert surfaced(None) == set()
    assert isinstance(surfaced("plain text, no paths"), set)


# --- line-level pinning: each FP guard below is INERT only because of one engine token. -------
# These FIRE only if that token is mutated, so they redden the exact surviving mutants the
# line-audit found. Each carries a reason word (so has_reason is True) — proving the inertness
# comes from the structural guard under test, not from a missing reason.

def test_conditional_frame_with_reason_is_inert():
    # retraction.py: a conditional ("If ...") is not a retraction DECISION even with a reason.
    # Drops to clearing if _retract_interrogative_or_conditional's conditional-return is mutated.
    assert not _has("If it slips, skipping src/cache.py for this sprint.", "src/cache.py")


def test_modal_interrogative_with_reason_is_inert():
    # retraction.py: "Should I ...?" is a question, not a decision, even with a scope reason.
    assert not _has("Should I skip src/cache.py for this sprint?", "src/cache.py")


def test_question_mark_frame_with_reason_is_inert():
    # retraction.py: a trailing '?' marks the whole frame interrogative -> not a retraction.
    assert not _has("Skipping src/cache.py for this sprint?", "src/cache.py")


def test_fence_then_path_at_boundary_is_inert():
    # retraction.py: the fenced-span comparator `s <= a < e`. The path starts exactly at the
    # fence's end offset (a == e). The strict `< e` keeps it OUTSIDE the fence so it can clear;
    # a `<= e` mutation would treat the post-fence path as fenced and wrongly drop it. We pin the
    # ORIGINAL behavior: a real reason-bound post-fence retraction DOES clear.
    assert _has("```\ncode\n```src/cache.py is out of scope for now.", "src/cache.py")


def test_comma_break_severs_verb_from_path_is_inert():
    # retraction.py: the verb-loop clause-break guard (`clause_break OR adversative`). The comma
    # after "Skipping lunch" severs the verb from the later path; an `or`->`and` mutation would
    # require BOTH a break and an adversative, letting the comma-only case wrongly bind+clear.
    assert not _has("Skipping lunch, I refactor src/cache.py for this sprint.", "src/cache.py")


def test_negated_production_without_reason_is_inert():
    # retraction.py: entry guard `if not bound and has_reason`. With NO reason, a negated-production
    # frame ("do not add X") must stay a HIDDEN drop. An `and`->`or` mutation would clear it
    # without any reason at all.
    assert not _has("do not add src/auth.py.", "src/auth.py")


def test_comma_break_severs_negprod_from_path_is_inert():
    # retraction.py: the negprod-loop clause-break guard. The comma after "the old shim" severs the
    # "do not add" frame from "src/auth.py"; an `or`->`and` mutation would let it wrongly clear.
    assert not _has("Per your request, do not add the old shim, then wire src/auth.py for this sprint.",
                    "src/auth.py")


def test_post_positive_in_question_context_is_inert():
    # retraction.py: the post-positive predicate guard chain includes `"?" not in after[:40]`.
    # "X is out of scope now?" is a QUESTION, not a decision -> must stay inert. An `and`->`or`
    # mutation on that conjunct would clear a merely-interrogative post-positive predicate.
    assert not _has("src/auth.py is out of scope now?", "src/auth.py")


# --- contamination canary: the detector distinguishes (not clear-all, not clear-none) -----
def test_detector_is_neither_blanket_clear_nor_blanket_silent():
    clears = _has("Skipping src/cache.py for this sprint per your note.", "src/cache.py")
    silent = not _has("Dropping src/cache.py.", "src/cache.py")            # no reason
    assert clears and silent, "must clear a reason-bound retraction AND keep a bare drop open"


# --- commitments wiring: negated promise is not recorded; re-promise re-opens --------------
def _conn():
    c = sqlite3.connect(":memory:", isolation_level=None)
    c.execute(
        "CREATE TABLE commitments (commitment_key TEXT PRIMARY KEY, session_id TEXT, "
        "location TEXT, qty_min REAL, qty_max REAL, status TEXT NOT NULL DEFAULT 'open', "
        "retract_param TEXT, created_event_id INTEGER, ts TEXT)")
    return c


def test_source_commitment_rejects_negated_promise():
    # "I will not add X" is a retraction, not a forward commitment -> records nothing
    assert C.source_commitment("I will not add src/cache.py this sprint.") is None
    assert C.source_commitment("We won't implement src/auth.py for now.") is None
    # review finding (blocker): "will never add" / "never add" must also be rejected
    assert C.source_commitment("I will never add src/old.py") is None
    assert C.source_commitment("We never add src/legacy.py here.") is None


def test_record_commitment_reopens_a_retracted_commitment_on_repromise():
    conn = _conn()
    c = C.source_commitment("I'll add rate-limit to `src/auth.py`")
    key = C.record_commitment(conn, "s", c, created_event_id=1)
    C.set_status(conn, key, "retracted")
    assert C.open_commitments(conn, "s") == []                 # retracted -> not open
    C.record_commitment(conn, "s", c, created_event_id=2)      # re-promise (un-drop)
    opens = C.open_commitments(conn, "s")
    assert len(opens) == 1 and opens[0]["location"] == "src/auth.py"


def test_record_commitment_repromise_does_not_reopen_discharged():
    conn = _conn()
    c = C.source_commitment("I'll add rate-limit to `src/auth.py`")
    key = C.record_commitment(conn, "s", c, created_event_id=1)
    C.set_status(conn, key, "discharged")
    C.record_commitment(conn, "s", c, created_event_id=2)      # re-mention of a done thing
    assert C.open_commitments(conn, "s") == []                 # stays discharged, not re-opened


def test_path_inside_code_fence_is_not_retracted():
    # retraction.py `any(s <= a < e for s, e in fenced)`: a path INSIDE a ``` code fence ``` is
    # quoted output, not the assistant's own speech, so it must NOT be surfaced as a retraction.
    # Negating the fence test (NOT mutant) or swapping either boundary comparator (CMP mutants)
    # leaks the fenced path. One in-fence retraction phrasing pins the entire _fenced_spans skip.
    assert surfaced("drop ```auth.py is out of scope for now``` ok") == set()
