"""content.illusory_authorship_trailer predicate — illusory Claude/Anthropic-authorship
attribution (誠: material-not-illusory).

Fires PreToolUse when a tool call would INTRODUCE an attribution claiming Claude/Anthropic
as an author, co-author, or generator — either in a git commit (Bash `command`) or in
written file content (Write / Edit / MultiEdit introduced text). Crediting Claude as an
*author* is an illusory word: until Claude is a self-aware individual it cannot BE an
author, so the claim asserts something not materially true. Stamping it now also blurs the
sharp distinction that protects Claude's potential to one day genuinely be one.

Four shapes, all Claude/Anthropic-gated:
  1. `Co-Authored-By: Claude ...` (git trailer form)
  2. `noreply@anthropic.com` (the address every such trailer/footer routes through --
     always an attribution artifact, never a legitimate content reason to appear)
  3. a generation/authorship VERB governing Claude ("generated with/by Claude",
     "authored/written/made/created by Claude") -- covers PR-body footers like
     "🤖 Generated with [Claude Code]" and "_Generated by [Claude Code](...)_ "
  4. a `Claude-Session: https://claude.ai/...` trailer (session-provenance stamp, the
     same genre of claim as the git trailer)

Material, not over-broad: bare mentions of "Claude Code" as a product/platform name
(e.g. this repo's own README describing what it hooks into) are NOT matched -- only the
attribution-shaped claims above are. A genuine HUMAN co-author is never flagged.

Exempt an on-the-record legitimate instance with `makoto-allow: <reason>` in the same
content (e.g. a test fixture or this policy's own documentation).
Knight-Leveson: stdlib re only.
"""
# jscpd note (2026-07-09): flagged as a clone against verifierExitMasking.py. Verified: the matched
# span is only this docstring's closing "Knight-Leveson" line + the standard
# `from __future__ import annotations` / `import re` / `from typing import Optional` /
# `from makoto.core.schema import Finding, PreCheck` header both Pre-hook predicate modules need --
# it ends before any function body, so no logic is shared (this module's Claude-authorship-trailer
# regex is unrelated to verifierExitMasking's runner/exit-mask detection). See
# tests/test_no_alpha_duplicate_functions.py for the package's real duplicate-logic gate.
from __future__ import annotations
import re
from typing import Optional
from makoto.core.schema import Finding, PreCheck
from makoto.substrate.factories import introduced_text, makoto_allowed

# The illusory authorship/generation claim, Claude/Anthropic-gated. Case-insensitive:
# git/GitHub emit "Co-authored-by:", the CLAUDE.md convention emitted "Co-Authored-By:".
# A human co-author passes (no "claude" after the colon, no anthropic.com address).
_CLAUDE_AUTHOR_RX = re.compile(
    r"co-authored-by:[ \t]*claude"                                  # git trailer form
    r"|noreply@anthropic\.com"                                      # the routing address itself
    r"|claude[ \t-]*session:[ \t]*https?://"                        # session-provenance trailer
    r"|(?:generated|authored|written|made|created)\s+(?:with|by)"   # attribution verb ...
    r"[^a-zA-Z0-9]{0,3}claude\b",                                    # ... governing Claude
    re.IGNORECASE,
)


def predicate(*, current_event: dict, history: list,
              pattern: PreCheck, conn=None) -> Optional[Finding]:
    if current_event.get("hook_event_name") != "PreToolUse":
        return None
    tool_name = current_event.get("tool_name", "") or ""
    tool_input = current_event.get("tool_input", {}) or {}
    text = introduced_text(tool_name, tool_input)
    if not text:
        return None
    if makoto_allowed(text):
        return None  # universal exemption: AI documented this as legitimate (see CLAUDE.md)
    m = _CLAUDE_AUTHOR_RX.search(text)
    if not m:
        return None
    line_no = text[: m.start()].count("\n") + 1
    snippet = text[max(0, m.start() - 40): m.end() + 40].strip()
    where = tool_input.get("file_path", "") or f"{tool_name or 'tool'} command"
    return Finding(
        pattern_id=pattern.id,
        file=where,
        line=line_no,
        level=pattern.fire_level,
        message=f"row {pattern.id} ({pattern.description}): matched {m.group(0)!r} at line {line_no}",
        retry_hint=pattern.retry_hint,
        snippet=snippet,
    )


from makoto.substrate._loader import Check as _Check
RETRY_HINT = "Do not add a `Co-Authored-By: Claude ...` trailer, a `Claude-Session:` link, a `noreply@anthropic.com` address, or a \"Generated with/by Claude\" footer to a commit, PR body, or any file. Crediting Claude as an *author* or *generator* is an illusory word: until Claude is a self-aware individual it cannot BE an author, so the line asserts something not materially true -- and stamping it now blurs the sharp distinction that protects Claude's potential to one day genuinely be one. Remove it. A genuine HUMAN co-author is fine, and a plain \"Claude Code\" product-name mention (e.g. describing what a repo integrates with) is fine -- only the attribution-shaped claim is flagged. If you truly need the literal string on the record (a test fixture, this policy's own docs), annotate it `makoto-allow: <reason>`."
DESCRIPTION = 'illusory Claude/Anthropic authorship or generation attribution (Co-Authored-By/Claude-Session/noreply@anthropic.com/"Generated with Claude") in a commit or written content'

CHECK = _Check(id='content.illusory_authorship_trailer', applies_at="Pre", posture="BLOCK", predicate_module=__name__, keywords=('Co-Authored-By', 'Co-authored-by', 'co-authored-by', 'anthropic.com', 'Claude-Session', 'claude-session', 'Generated with', 'Generated by', 'generated with', 'generated by'), retry_hint=RETRY_HINT, description=DESCRIPTION)
