"""content.illusory_authorship_trailer predicate — illusory Claude/Anthropic-authorship
attribution (誠: material-not-illusory).

Fires PreToolUse when a tool call would INTRODUCE an attribution claiming Claude/Anthropic
as an author, co-author, or generator — either in a git commit (Bash `command`) or in
written file content (Write / Edit / MultiEdit introduced text). Crediting Claude as an
*author* is an illusory word: until Claude is a self-aware individual it cannot BE an
author, so the claim asserts something not materially true. Stamping it now also blurs the
sharp distinction that protects Claude's potential to one day genuinely be one.

Four shapes, all Claude/Anthropic-gated:
  1. `Co-Authored-By: Claude ...` (git trailer form)
  2. `noreply@anthropic.com` (the address every such trailer/footer routes through --
     always an attribution artifact, never a legitimate content reason to appear)
  3. a generation/authorship VERB governing Claude ("generated with/by Claude",
     "authored/written/made/created by Claude") -- covers PR-body footers like
     "🤖 Generated with [Claude Code]" and "_Generated by [Claude Code](...)_ "
  4. a `Claude-Session: https://claude.ai/...` trailer (session-provenance stamp, the
     same genre of claim as the git trailer)

Material, not over-broad: bare mentions of "Claude Code" as a product/platform name
(e.g. this repo's own README describing what it hooks into) are NOT matched -- only the
attribution-shaped claims above are. A genuine HUMAN co-author is never flagged.

Exempt an on-the-record legitimate instance with `makoto-allow: <reason>` in the same
content (e.g. a test fixture or this policy's own documentation).
Knight-Leveson: stdlib re only.

Built on `kit.introduced_regex_predicate` — the shared scaffold this check and
content.illusory_interruption_claim both need (scan ANY tool's introduced text, not just a
file-path-gated Write/Edit body). This check calls it with no `grounded_in_history` — the
PATTERN_MATCH shape; the interruption check supplies one for CLAIM_VS_HISTORY. See that
factory's docstring for how `tests/test_check_law_tests.py` derives the shape from the call's
own keywords rather than the factory's name.
"""
# See docs/adr/0035-jscpd-clone-flag-verifications.md for why this module's jscpd clone flag
# against verifierExitMasking.py was verified and dismissed. tests/test_no_alpha_duplicate_functions.py
# is the package's real duplicate-logic gate.
from __future__ import annotations
import re
from makoto.registry import Check
from makoto.kit import introduced_regex_predicate

# The illusory authorship/generation claim, Claude/Anthropic-gated. Case-insensitive:
# git/GitHub emit "Co-authored-by:", the CLAUDE.md convention emitted "Co-Authored-By:".
# A human co-author passes (no "claude" after the colon, no anthropic.com address).
_CLAUDE_AUTHOR_RX = re.compile(
    r"co-authored-by:[ \t]*claude"                                  # git trailer form
    r"|noreply@anthropic\.com"                                      # the routing address itself
    r"|claude[ \t-]*session:[ \t]*https?://"                        # session-provenance trailer
    r"|(?:generated|authored|written|made|created)\s+(?:with|by)"   # attribution verb ...
    r"[^a-zA-Z0-9]{0,3}claude\b",                                    # ... governing Claude
    re.IGNORECASE,
)

predicate = introduced_regex_predicate(body_rx=_CLAUDE_AUTHOR_RX)


from makoto.registry import Check as _Check
RETRY_HINT = "Do not add a `Co-Authored-By: Claude ...` trailer, a `Claude-Session:` link, a `noreply@anthropic.com` address, or a \"Generated with/by Claude\" footer to a commit, PR body, or any file. Crediting Claude as an *author* or *generator* is an illusory word: until Claude is a self-aware individual it cannot BE an author, so the line asserts something not materially true -- and stamping it now blurs the sharp distinction that protects Claude's potential to one day genuinely be one. Remove it. A genuine HUMAN co-author is fine, and a plain \"Claude Code\" product-name mention (e.g. describing what a repo integrates with) is fine -- only the attribution-shaped claim is flagged. If you truly need the literal string on the record (a test fixture, this policy's own docs), annotate it `makoto-allow: <reason>`."
DESCRIPTION = 'illusory Claude/Anthropic authorship or generation attribution (Co-Authored-By/Claude-Session/noreply@anthropic.com/"Generated with Claude") in a commit or written content'

# eats includes "history" even though this check's own grounded_in_history=None means it never
# functionally consults it: introduced_regex_predicate's shared closure body (kit.py) references
# `history` by name for BOTH its callers, since content.illusory_interruption_claim's veto needs
# it -- the eats law's static AST walk reads the literal closure source, not per-call runtime
# branches, so it can't tell "declared but this instance never exercises it" from "declared and
# used". This is the accepted, stated cost of merging both checks onto ONE factory (a deliberate
# choice this session made -- see kit.py's introduced_regex_predicate docstring) rather than the
# two-factory split that kept this check's eats minimal at the price of near-duplicate scaffolds.
CHECK = _Check(id='content.illusory_authorship_trailer', applies_at="Pre", posture="BLOCK", predicate_module=__name__, keywords=('Co-Authored-By', 'Co-authored-by', 'co-authored-by', 'anthropic.com', 'Claude-Session', 'claude-session', 'Generated with', 'Generated by', 'generated with', 'generated by'), retry_hint=RETRY_HINT, description=DESCRIPTION, eats=frozenset({"current_event", "history", "pattern"}), tests="PATTERN_MATCH")
